/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Cycle_aliases.h"
#include "Cycle.h"
#include "Confirm_aliases.h"
#include "Confirm.h"
#include "Overwrite_aliases.h"
#include "Overwrite.h"
#include "Forward_aliases.h"
#include "Forward.h"
#include "Back_aliases.h"
#include "Back.h"
#include "ICPCK_ISR.h"
#include "LCD_I2C_FUNCS.h"
#include "LCD_I2C_LL_I2C.h"
#include "LCD_I2C_REGS.h"
#include "UART.h"
#include "ICPCK_aliases.h"
#include "ICPCK.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "Motor_aliases.h"
#include "Motor.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "MotorCLK.h"
#include "MotorTimer.h"
#include "MotorISR.h"
#include "ENC_aliases.h"
#include "ENC.h"
#include "ENCISR.h"
#include "DebounceCLK.h"
#include "CycleISR.h"
#include "ConfirmISR.h"
#include "OverwriteISR.h"
#include "ForwardISR.h"
#include "BackISR.h"
#include "Solenoid_aliases.h"
#include "Solenoid.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

